declare const token: string;
declare const ownerID: string;
declare const Discord: any;
declare const client: any;
declare const config: any;
declare const prefix: any;
declare const colors: any;
declare const promisify: any;
declare const readdir: any;
declare const Enmap: any;
declare const SQLite: any;
declare var version: string;
declare const defaultSettings: {
    prefix: string;
    modLogChannel: string;
    messageLogChannel: string;
    userLogChannel: string;
    guildLogChannel: string;
    clientLogChannel: string;
    welcomeChannel: string;
    welcomeMessage: string;
    leaveChannel: string;
    leaveMessage: string;
    starboardChannel: string;
    pinboardChannel: string;
    modRole: string;
    adminRole: string;
    muteRole: string;
    verifyRole: string;
    restrictRole: string;
    timezone: string;
    levelToggle: string;
};
declare const subDirectory: string[];
declare const init: () => Promise<void>;
